definitions:
  exchange_rate.ConversionResponse:
    properties:
      amount:
        type: string
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/exchange-rate/{source}/conversion/{target}:
    get:
      description: exchange rate conversion
      parameters:
      - description: source currency
        enum:
        - JPY
        - TWD
        - USD
        in: path
        name: source
        required: true
        type: string
      - description: target currency
        enum:
        - JPY
        - TWD
        - USD
        in: path
        name: target
        required: true
        type: string
      - description: amount
        example: '"$1,111.05"'
        in: query
        name: amount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/exchange_rate.ConversionResponse'
        "400":
          description: Bad parameter" example({message="bad parameter",amount="0"})
          schema:
            $ref: '#/definitions/exchange_rate.ConversionResponse'
      summary: exchange rate conversion
      tags:
      - exchange rate
swagger: "2.0"
